name: Build macOS
on: [push]
jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Init Homebrew
        run: |
          eval "$(/opt/homebrew/bin/brew shellenv)" || eval "$(/usr/local/bin/brew shellenv)"
          echo "PATH=$PATH" >> $GITHUB_ENV
      - name: "Run script"
        run: ./ci/build.sh
        shell: bash
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          DEV_APP_ID: ${{ secrets.DEV_APP_ID }}
          APPLICATION: ${{ secrets.APPLICATION }}
          INSTALLER: ${{ secrets.INSTALLER }}
          DEV_INST_ID: ${{ secrets.DEV_INST_ID }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
          APPLE_USER: ${{ secrets.APPLE_USER }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ultraView-macos
          path: ci/bin/ultraView_*.pkg
          archive: false
