name: Build Windows
on: [push]
jobs:
  build:
    name: Build Windows
    runs-on: windows-2025-vs2026
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash

      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y
        shell: bash

      - name: "Run script"
        run: ./ci/build.sh
        shell: bash
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
          AZURE_CERT_PROFILE: ${{ secrets.AZURE_CERT_PROFILE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ultraView-windows
          path: ci/bin/ultraView_*.exe
          archive: false
