name: Build Windows
on: [push]
jobs:
  build:
    name: Build Windows
    runs-on: windows-2025-vs2026
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Run script"
        run: ./ci/build.sh
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Binaries windows_ultraView
          path: bin/*
          retention-days: 30
